# Site settings
title: Nimbus Workspaces
description: 'Para você ter seu portfólio de projetos sob controle e instigar a interdependência de seus clientes e colaboradores, pela interface ágil da nossa plataforma de gestão de documentos, pessoas e fluxos no setor de Arquitetura, Engenharia e Construção (AEC).'
url: '{{ site.github.url }}'
baseurl: '/'
google_analytics: 'UA-53935109-1'
# disqus_shortname: 'your-disqus-name'

contact:
  name: 'Equipe Nimbus'
  email: equipe@nimbusws.com.br
  # facebook_username: nimbus
  # instagram_username: nimbus

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
